set echo off
set feedback off

-- spool 
SET LINESIZE 80
SET PAGESIZE 30

CLEAR COLUMNS

-- the – means continue the command on the next line
TTITLE CENTER 'Books in Inventory' SKIP -
  RIGHT 'Page:' FORMAT 9 SQL.PNO SKIP 2
BTITLE LEFT 'Generated by:' FORMAT A10 SQL.USER CENTER 'For internal use only'

SELECT ISBN, initcap(TITLE) "Title"
FROM books
ORDER BY title;

-- spool off
set feedback on
set echo on

